server:
 host: 0.0.0.0
 port: 8899
mocks_path: ./mocks


token-generator:
   password:
     type: Password-Credential
     token-url:  
     client-id: 
     client-secret: 
     username: 
     password: 
     scope: read
   client:
     type: Client-Credential
     token-url:  
     client-id: 
     client-secret: 
     scope: admin