name: Test & Build

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17.5']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run Tests...
        run: go test -v -vet=off -race ./...
      - name: Build...
        run: go build -race cmd/lara/main.go